### ISSUE TITLE
story(storage): support apache cassandra for recording events

### ISSUE THREAD

**Issue by Zaba505** [z5labs/evrys#25]
### Description

As an end user, I want evrys to record events to Apache Cassandra, so that I can deploy evrys in a cloud agnostic way.

### Acceptance Criteria

- [ ] Define PutEvent interface
- [ ] Implement PutEvent interface for Apache Cassandra
- [ ] Implement integration tests

**Comment by erictg** [comment]
Determined cassandra data representation does not support the data model. Cassandra does not natively support generic fields, as required by our data model
